site_name: The AI Engineer Handbook - a practical, hands-on guide
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.prune 
    - toc.follow
    - toc.integrate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true